"""Add patient_public_id to Study

Revision ID: c9636c83d83c
Revises: 0003_nifti_demo
Create Date: 2026-08-09 15:32:30.616709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9636c83d83c'
down_revision: Union[str, None] = '0003_nifti_demo'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_public_id'), table_name='jobs')
    op.create_index(op.f('ix_jobs_public_id'), 'jobs', ['public_id'], unique=True)
    op.drop_index(op.f('ix_series_series_instance_uid'), table_name='series')
    op.create_index(op.f('ix_series_series_instance_uid'), 'series', ['series_instance_uid'], unique=True)
    op.add_column('studies', sa.Column('patient_public_id', sa.Uuid(), nullable=False))
    op.drop_index(op.f('ix_studies_public_id'), table_name='studies')
    op.create_index(op.f('ix_studies_public_id'), 'studies', ['public_id'], unique=True)
    op.drop_index(op.f('ix_studies_study_instance_uid'), table_name='studies')
    op.create_index(op.f('ix_studies_study_instance_uid'), 'studies', ['study_instance_uid'], unique=True)
    op.create_index(op.f('ix_studies_patient_public_id'), 'studies', ['patient_public_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_studies_patient_public_id'), table_name='studies')
    op.drop_index(op.f('ix_studies_study_instance_uid'), table_name='studies')
    op.create_index(op.f('ix_studies_study_instance_uid'), 'studies', ['study_instance_uid'], unique=False)
    op.drop_index(op.f('ix_studies_public_id'), table_name='studies')
    op.create_index(op.f('ix_studies_public_id'), 'studies', ['public_id'], unique=False)
    op.drop_column('studies', 'patient_public_id')
    op.drop_index(op.f('ix_series_series_instance_uid'), table_name='series')
    op.create_index(op.f('ix_series_series_instance_uid'), 'series', ['series_instance_uid'], unique=False)
    op.drop_index(op.f('ix_jobs_public_id'), table_name='jobs')
    op.create_index(op.f('ix_jobs_public_id'), 'jobs', ['public_id'], unique=False)
    # ### end Alembic commands ###
